/** AUTO-GENERATED by scripts/optimize-photos.mjs — do not edit */
export const photoLibraryStats = {
  total: 68,
  featured: 17,
  slotOutputs: 17,
  petFolders: 1,
  generatedAt: "2026-06-12T13:02:23.620Z",
} as const;

export type PhotoLibraryEntry = {
  src: string;
  alt: string;
  folder: string;
};

export const photoLibrary: PhotoLibraryEntry[] = [
  {
    "src": "/pictures/library/img-3292.webp",
    "alt": "Keep Waco Wagging — IMG_3292",
    "folder": "uploads"
  },
  {
    "src": "/pictures/library/img-9496.webp",
    "alt": "Keep Waco Wagging — IMG_9496",
    "folder": "uploads"
  },
  {
    "src": "/pictures/library/freddie-img-4785.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/scooping-diesel.webp",
    "alt": "Scooping — Waco dog life",
    "folder": "scooping"
  },
  {
    "src": "/pictures/library/founders-jackye-and-todd.webp",
    "alt": "Founders — Waco dog life",
    "folder": "founders"
  },
  {
    "src": "/pictures/library/boarding-home-shi-and-diesel.webp",
    "alt": "Boarding Home — Waco dog life",
    "folder": "boarding-home"
  },
  {
    "src": "/pictures/library/boarding-indoor-diesel1.webp",
    "alt": "Boarding Indoor — Waco dog life",
    "folder": "boarding-indoor"
  },
  {
    "src": "/pictures/library/training-stella-puzzlw.webp",
    "alt": "Training — Waco dog life",
    "folder": "training"
  },
  {
    "src": "/pictures/library/boarding-backyard-img-5285.webp",
    "alt": "Boarding Backyard — Waco dog life",
    "folder": "boarding-backyard"
  },
  {
    "src": "/pictures/library/img-3738.webp",
    "alt": "Keep Waco Wagging — IMG_3738",
    "folder": "uploads"
  },
  {
    "src": "/pictures/library/img-4814.webp",
    "alt": "Keep Waco Wagging — IMG_4814",
    "folder": "uploads"
  },
  {
    "src": "/pictures/library/freddie-img-4910.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/hero-stella-diesel-walkies.webp",
    "alt": "Hero — Waco dog life",
    "folder": "hero"
  },
  {
    "src": "/pictures/library/img-2683.webp",
    "alt": "Keep Waco Wagging — IMG_2683",
    "folder": "uploads"
  },
  {
    "src": "/pictures/library/freddie-img-4924.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/img-8954.webp",
    "alt": "Keep Waco Wagging — IMG_8954",
    "folder": "uploads"
  },
  {
    "src": "/pictures/library/img-4813.webp",
    "alt": "Keep Waco Wagging — IMG_4813",
    "folder": "uploads"
  },
  {
    "src": "/pictures/library/freddie-img-2462.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-2463.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-2465.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-2466.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-2569.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-2658.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-2660.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4784.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4786.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4787.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4788.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4789.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4866.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4905.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4906.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4907.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4908.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4909.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4911.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4914.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4915.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4916.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4917.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4918.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4919.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4920.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4921.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4922.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4923.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4925.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4926.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4927.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/freddie-img-4928.webp",
    "alt": "Freddie — Waco dog life",
    "folder": "Freddie"
  },
  {
    "src": "/pictures/library/img-0037.webp",
    "alt": "Keep Waco Wagging — IMG_0037",
    "folder": "uploads"
  },
  {
    "src": "/pictures/library/img-0728.webp",
    "alt": "Keep Waco Wagging — IMG_0728",
    "folder": "uploads"
  },
  {
    "src": "/pictures/library/img-0729.webp",
    "alt": "Keep Waco Wagging — IMG_0729",
    "folder": "uploads"
  },
  {
    "src": "/pictures/library/img-0912.webp",
    "alt": "Keep Waco Wagging — IMG_0912",
    "folder": "uploads"
  },
  {
    "src": "/pictures/library/img-0916.webp",
    "alt": "Keep Waco Wagging — IMG_0916",
    "folder": "uploads"
  },
  {
    "src": "/pictures/library/img-0943.webp",
    "alt": "Keep Waco Wagging — IMG_0943",
    "folder": "uploads"
  },
  {
    "src": "/pictures/library/img-1007.webp",
    "alt": "Keep Waco Wagging — IMG_1007",
    "folder": "uploads"
  },
  {
    "src": "/pictures/library/img-1338.webp",
    "alt": "Keep Waco Wagging — IMG_1338",
    "folder": "uploads"
  },
  {
    "src": "/pictures/library/img-1506.webp",
    "alt": "Keep Waco Wagging — IMG_1506",
    "folder": "uploads"
  },
  {
    "src": "/pictures/library/img-3285.webp",
    "alt": "Keep Waco Wagging — IMG_3285",
    "folder": "uploads"
  },
  {
    "src": "/pictures/library/img-3291.webp",
    "alt": "Keep Waco Wagging — IMG_3291",
    "folder": "uploads"
  },
  {
    "src": "/pictures/library/img-3305.webp",
    "alt": "Keep Waco Wagging — IMG_3305",
    "folder": "uploads"
  },
  {
    "src": "/pictures/library/img-3675.webp",
    "alt": "Keep Waco Wagging — IMG_3675",
    "folder": "uploads"
  },
  {
    "src": "/pictures/library/img-3678.webp",
    "alt": "Keep Waco Wagging — IMG_3678",
    "folder": "uploads"
  },
  {
    "src": "/pictures/library/pets-diesel-diesel1.webp",
    "alt": "Pets Diesel — Waco dog life",
    "folder": "pets-diesel"
  },
  {
    "src": "/pictures/library/pets-scoop-diesel.webp",
    "alt": "Pets Scoop — Waco dog life",
    "folder": "pets-scoop"
  },
  {
    "src": "/pictures/library/pets-shiloh-shi-and-diesel.webp",
    "alt": "Pets Shiloh — Waco dog life",
    "folder": "pets-shiloh"
  },
  {
    "src": "/pictures/library/pets-stella-stella-puzzlw.webp",
    "alt": "Pets Stella — Waco dog life",
    "folder": "pets-stella"
  }
];

export type PetFolderPhoto = {
  folder: string;
  slug: string;
  photoUrl: string;
  count: number;
};

export const petFolderPhotos: PetFolderPhoto[] = [
  {
    "folder": "Freddie",
    "slug": "freddie",
    "photoUrl": "/pets/freddie.webp",
    "count": 36
  }
];

export function getPhotoByIndex(index: number): PhotoLibraryEntry {
  return photoLibrary[index % photoLibrary.length]!;
}
